name: open_meteo_api
description: "Dart API client for the Open-Meteo API"
version: 0.0.1

environment:
  sdk: ^3.5.3

dependencies:
  http: ^1.2.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.8
