name: weather_repository
description: "A Dart Repository which manages the weather domain."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  open_meteo_api:
    path: ../open_meteo_api

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.8
  coverage: ^1.9.2
